import { createClient } from '@supabase/supabase-js';
import PDFDocument from 'pdfkit';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

const BRAND_DARK = '#0a1628';
const BRAND_CYAN = '#76fbd3';
const TEXT_MAIN = '#1e293b';
const TEXT_MUTED = '#64748b';

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { scan_id } = req.query;

    if (!scan_id) {
      return res.status(400).json({ error: 'Missing required parameter: scan_id' });
    }

    const { data: scan, error: fetchError } = await supabase
      .from('ai_scans')
      .select('*')
      .eq('id', scan_id)
      .single();

    if (fetchError || !scan) {
      console.error('Supabase fetch error:', fetchError);
      return res.status(404).json({ error: 'System Audit Record not found' });
    }

    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 0, bottom: 50, left: 50, right: 50 },
      info: {
        Title: `ComplianceGuard AI Audit Report - ${scan.model_name}`,
        Author: 'ComplianceGuard AI',
        Subject: 'EU AI Act Liability Assessment',
      }
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="ComplianceGuard_Audit_${scan_id}.pdf"`);

    doc.pipe(res);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const marginLeft = 50;
    const marginRight = 50;
    const marginBottom = 80;
    const contentWidth = pageWidth - marginLeft - marginRight;

    let currentY = 50;
    let pageNumber = 1;

    const addWatermark = () => {
      doc.save();
      doc.opacity(0.04);
      const watermarkText = 'COMPLIANCEGUARD';
      const watermarkSize = 50;
      const textWidth = doc.widthOfString(watermarkText, { fontSize: watermarkSize, font: 'Helvetica-Bold' });
      
      doc.fontSize(watermarkSize)
         .fillColor(BRAND_DARK)
         .font('Helvetica-Bold')
         .text(watermarkText, (pageWidth - textWidth) / 2, pageHeight / 2 - 30);
      
      doc.opacity(1);
      doc.restore();
    };

    const addHeader = () => {
      doc.rect(0, 0, pageWidth, 110).fill(BRAND_DARK);
      
      doc.fontSize(22)
         .fillColor(BRAND_CYAN)
         .font('Helvetica-Bold')
         .text('COMPLIANCEGUARD AI', marginLeft, 35);
         
      doc.fontSize(10)
         .fillColor('#ffffff')
         .font('Helvetica')
         .text('ENTERPRISE COMPLIANCE & LIABILITY AUDIT', marginLeft, 65, { opacity: 0.8 });

      const reportDate = scan.created_at ? new Date(scan.created_at).toLocaleDateString('en-GB') : new Date().toLocaleDateString();
      doc.fontSize(9)
         .fillColor('#ffffff')
         .text(`REPORT ID: ${scan_id.substring(0, 8).toUpperCase()}`, pageWidth - marginRight - 150, 40, { align: 'right', width: 150 })
         .text(`DATE: ${reportDate}`, pageWidth - marginRight - 150, 55, { align: 'right', width: 150 });

      currentY = 140;
    };

    const addFooter = () => {
      const footerY = pageHeight - 50;
      doc.save();
      doc.moveTo(marginLeft, footerY - 10).lineTo(pageWidth - marginRight, footerY - 10).strokeColor('#e2e8f0').lineWidth(1).stroke();
      doc.fontSize(8).fillColor(TEXT_MUTED).font('Helvetica').text(`Page ${pageNumber}`, marginLeft, footerY, { width: contentWidth, align: 'center' });
      doc.fontSize(7).fillColor('#94a3b8').text('CONFIDENTIAL. Generated by ComplianceGuard AI. Strict EU AI Act Guidelines Apply.', marginLeft, footerY + 15, { width: contentWidth, align: 'center' });
      doc.restore();
    };

    const checkPageBreak = (requiredSpace = 100) => {
      if (currentY + requiredSpace > pageHeight - marginBottom) {
        addFooter();
        doc.addPage();
        pageNumber++;
        addHeader();
        addWatermark();
        return true;
      }
      return false;
    };

    const addSectionHeading = (title, topMargin = 20) => {
      checkPageBreak(60);
      currentY += topMargin;
      doc.fontSize(14).fillColor(BRAND_DARK).font('Helvetica-Bold').text(title.toUpperCase(), marginLeft, currentY);
      doc.moveTo(marginLeft, currentY + 18).lineTo(pageWidth - marginRight, currentY + 18).strokeColor('#e2e8f0').lineWidth(1).stroke();
      currentY += 35;
    };

    addHeader();
    addWatermark();

    addSectionHeading('System Target Identification', 0);

    const metadata = [
      ['Target Model Name:', scan.model_name || 'Unidentified Neural Net'],
      ['Deployment Sector:', scan.industry || 'Global Operations'],
      ['Scan Origin:', 'ComplianceGuard AI Security Engine']
    ];

    metadata.forEach(([label, value]) => {
      checkPageBreak(25);
      doc.fontSize(10).fillColor(TEXT_MUTED).font('Helvetica-Bold').text(label, marginLeft, currentY, { width: 150, continued: false });
      doc.fontSize(10).fillColor(TEXT_MAIN).font('Helvetica').text(value, marginLeft + 150, currentY, { width: contentWidth - 150 });
      currentY += 20;
    });

    currentY += 15;

    checkPageBreak(120);
    const isCompliant = scan.compliance_status;
    const boxBgColor = isCompliant ? '#ecfdf5' : '#fef2f2';
    const boxBorderColor = isCompliant ? '#10b981' : '#ef4444';
    const boxTextColor = isCompliant ? '#065f46' : '#991b1b';

    doc.rect(marginLeft, currentY, contentWidth, 80).fill(boxBgColor);
    doc.rect(marginLeft, currentY, contentWidth, 80).strokeColor(boxBorderColor).lineWidth(2).stroke();

    doc.fillColor(boxTextColor).fontSize(16).font('Helvetica-Bold').text(`AUDIT STATUS: ${isCompliant ? 'COMPLIANT & CLEARED' : 'CRITICAL NON-COMPLIANCE DETECTED'}`, marginLeft + 20, currentY + 20);
    doc.fontSize(11).font('Helvetica').text(`Identified Risk Vector: ${scan.risk_tier || 'High Risk Liability'}`, marginLeft + 20, currentY + 45);
    
    currentY += 110;

    addSectionHeading('Liability Threat Narrative');
    let summaryText = scan.summary || 'Awaiting deep structural analysis.';
    if (summaryText === 'Evaluating...') {
      summaryText = 'The ComplianceGuard AI logic core is currently processing the neural weight assessments. Full audit trail will be generated shortly. Ensure systems are sandboxed in the interim.';
    }

    const summaryHeight = doc.heightOfString(summaryText, { width: contentWidth, align: 'justify' });
    checkPageBreak(summaryHeight + 20);
    doc.fontSize(10).fillColor(TEXT_MAIN).font('Helvetica').text(summaryText, marginLeft, currentY, { width: contentWidth, align: 'justify', lineGap: 4 });
    currentY += summaryHeight + 40;

    addSectionHeading('Required Remediation Deployments');

    if (scan.remediation_steps && Array.isArray(scan.remediation_steps) && scan.remediation_steps.length > 0) {
      scan.remediation_steps.forEach((step, index) => {
        const stepDescHeight = doc.heightOfString(step.description || '', { width: contentWidth - 30, align: 'justify' });
        const totalStepHeight = 40 + stepDescHeight + 35; 

        checkPageBreak(totalStepHeight);

        doc.rect(marginLeft, currentY, contentWidth, totalStepHeight - 10).fill('#f8fafc');
        doc.rect(marginLeft, currentY, contentWidth, totalStepHeight - 10).strokeColor('#cbd5e1').lineWidth(1).stroke();

        doc.rect(marginLeft, currentY, 5, totalStepHeight - 10).fill('#f59e0b');

        let innerY = currentY + 15;
        
        doc.fontSize(11).fillColor('#b45309').font('Helvetica-Bold').text(`[LOCKED MODULE] Step ${step.step || index + 1}: ${step.title}`, marginLeft + 20, innerY, { width: contentWidth - 30 });
        innerY += 20;

        doc.fontSize(9).fillColor('#ef4444').font('Helvetica-Bold').text(`Priority: ${step.priority}   |   Sector: ${step.category}`, marginLeft + 20, innerY);
        innerY += 20;

        const fullDesc = step.description || '';
        const teaserText = fullDesc.split('. ')[0] + '...';
        
        doc.fontSize(10).fillColor(TEXT_MAIN).font('Helvetica').text(teaserText, marginLeft + 20, innerY, { width: contentWidth - 40, align: 'justify' });
        
        innerY += 30;
        doc.fontSize(9).fillColor('#0369a1').font('Helvetica-Bold').text('» UPGRADE TO COMPLIANCEGUARD PREMIUM TO DEPLOY THIS MITIGATION SCRIPT', marginLeft + 20, innerY);

        currentY += totalStepHeight;
      });
    } else {
      checkPageBreak(40);
      doc.fontSize(10).fillColor(TEXT_MUTED).font('Helvetica-Oblique').text('System shows no actionable remediation triggers at this clearance level.', marginLeft, currentY, { width: contentWidth });
      currentY += 30;
    }

    addFooter();
    doc.end();

  } catch (error) {
    console.error('Error generating PDF:', error);
    if (!res.headersSent) {
      return res.status(500).json({ success: false, error: 'Internal server error compiling PDF blueprint' });
    }
  }
}